# constants.py

# физика игры
GRAVITY = 15
JUMP_FORCE = GRAVITY * 2.5  # -37.5
MOVEMENT_SPEED = 7
CAMERA_OFFSET_SPEED = 7
PARALLAX_SPEED = 2

# размеры экрана и игровых объектов
SCREEN_WIDTH = 600
SCREEN_HEIGHT = 600
PLAYER_SIZE = 64
PORTAL_WIDTH = 64
PORTAL_HEIGHT = 128

# параметры камеры
CAMERA_CENTER_X = 300 - 75
CAMERA_CENTER_Y = 300 - 40
CAMERA_WIDTH = 150
CAMERA_HEIGHT = 80

# анимация
PLAYER_RUN_FRAMES = 20
PLAYER_FALL_FRAMES = 10

# звук
LEVER_VOLUME = 0.3
PORTAL_VOLUME = 0.05
MUSIC_VOLUME = 0.1

# интерфейс
INDICATOR_CIRCLE_RADIUS = 20
INDICATOR_CIRCLE_OFFSET = 42
INDICATOR_Y_POSITION = 30

# коллизии и физика
PORTAL_SIDE_OFFSET = 30
PORTAL_TELEPORT_DISTANCE = 70
INTERACTION_RANGE = 70
PARALLAX_DIVIDER = 0.85

# вероятности
OLEG_SPEAK_CHANCE = 12  # 1 из 12

# границы фона
BACKGROUND_RESET_LIMIT = 600

# константы для меню
MENU_WIDTH = 800
MENU_HEIGHT = 600
MENU_TEXT_START_Y = 100
MENU_TEXT_SPACING = 10
MENU_TEXT_BASE_X = 60
MENU_TEXT_OFFSET_MULTIPLIER = 4
